# Generated by Django 3.2 on 2021-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topoftheweek',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
