# Generated by Django 3.2 on 2021-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_topoftheweek_news_top_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='top_of_the_week',
            field=models.BooleanField(blank=True, default=False, verbose_name='Top'),
        ),
    ]
