# Generated by Django 3.2 on 2021-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_news_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('gadgets', 'Gadgets'), ('games', 'Games'), ('stream', 'Stream')], max_length=10),
        ),
    ]
