# Generated by Django 3.2 on 2021-04-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='editors_pick',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pick'),
        ),
    ]
